### ISSUE TITLE
CM12.1 Progress 

### ISSUE THREAD

**Issue by mknrls** [adt1-dev/android_device_google_molly#2]
These Issues Apply To Both CM- 12.1 & CM-13.0 Builds Unless Otherwise Noted 
## Functional (works):
- Wifi
- Gamepad Pairing
- ADB & MTP (PTP as well)
- Google Play Store (downloading and installing apps)
- Video Playback
- Audio
- Bluetooth
- Full LED Customization (Thanks to @r3pwn for writing the LED driver!)
- SE Linux Enforcing
- DRM (Including Leanback Netflix via Nexus 9 blobs)
- Back Button /should/ be remappable
- Control-able via the ATV Remote App
- Screen Casting - All apps! Better than Stock!
## Issues:
- Nexus Player Remote won't pair -- working on it (there is no hope of remote Mic due to CAF changes, could work on an AOSP build though)
## Wishlist:
- ?
### CM12.1:

TV Build - https://drive.google.com/file/d/0B8us3BLI5teOQVprSi02Sk5OTFE/view?usp=docslist_api
Tablet Build - Link Coming Soon
### CM13.0:

TV Build - Link Coming Soon
Tablet Build - Link Coming Soon
### PureNexus (MM)

TV Build - Link Coming Soon
Tablet Build - Link Coming Soon
### CM-12.1 TV -

https://drive.google.com/file/d/0B8us3BLI5teOaWtjSUdpZ2puRXc/view?usp=docslist_api
### CM-12.1 Tablet -

OpenGApps.org (Select 5.1/ARM/Mini Package)
### CM-13.0 TV -

Link Coming Soon
### CM-13.0 Tablet -

OpenGApps.org (Select 6.0/ARM/Mini Package)
### PureNexus (MM) TV -

Link Coming Soon
### PureNexus (MM) Tablet -

Link Coming Soon (Don't use OpenGApps)

**Comment by npjohnson** [comment]
WiFi, ADB, and DPI are fixed after tonight, but add: Audio, SELinux Light Control, and keep MTP on the list.

**Comment by r3pwn** [comment]
After last night, the issue with the apps crashing has been fixed and there are no more Setup issues. However, Bluetooth automatically broke itself. :/

**Comment by C457** [comment]
adb and mtp has been enabled

**Comment by r3pwn** [comment]
@C457 I updated the post, I think you can too.

**Comment by mknrls** [comment]
all of you can edit anything in repo, your all admins (owners).

**Comment by mattgorski** [comment]
I see there is a branch now called cm-12.1-audio 

Does this mean HDMI Audio is fixed?

**Comment by mknrls** [comment]
@Gfunk117 no its not fixed yet, it was more of a testing branch attempting to fix it

**Comment by r3pwn** [comment]
@Gfunk117 Exactly what @mknrls

**Comment by mattgorski** [comment]
Well I have one fugu and two mollys to test with.  What can I do to help?  I see you ported HAL from fugu...

**Comment by mknrls** [comment]
@Gfunk117 currently we need more experienced dev or devs to fix the audio or that we figure it sometime soon. 

Do you have any experience in rom/android development ect?

**Comment by mattgorski** [comment]
I have some experience.  I've compiled custom kernels for various USB devices for all my nexus devices, manta, hammerhead, fugu.  I've also built custom cm/cyanogenmod roms.  I also have knowledge in linux4tegra.  I've patched kernels for kexec hardbooting into Linux/Ubuntu for Linux development...

**Comment by mattgorski** [comment]
Thanks for adding me to the team.  I'm building molly userdebug right now.  I'll do some debugging on my build and report back.  I've got some ideas to test out.

**Comment by death2all110** [comment]
Hi Guys. Any updates on 12.1 or is the focus now on 13?

**Comment by mknrls** [comment]
@death2all110 cm13 doesn't even make it to the boot animation. 
cm12.1 > Audio: WIP & LED/Rear Button: WIP

**Comment by npjohnson** [comment]
Thanks in a large part to Matt, we have HDMI Audio!
Greg got LED Control working, but TungstenLED fails sig checks, so we have to disable those, and lo-and behold, that fixed BT, and rear-button! 

Now we just have to fix SE Linux and get past these sig check issues! Then we are there!

**Comment by speakxj7** [comment]
🙌🙇🙌🙇👍

**Comment by npjohnson** [comment]
Signature Issues are fixed after today! Thanks to @Gfunk117 ! We have rear button and minimal LED (Hardcoded) control. BT also works.

**Comment by npjohnson** [comment]
Did not intend to close this, my appologies

**Comment by spipnl** [comment]
I tried CM 12.1 yesterday and it worked very well on my ADT-1.
Some things I noticed:
- After install and optimizing apps it kept saying 'Finishing boot'. I had to hard reset the device, but then it worked fine.
- I could not get Netflix to work and after installing it once I could not uninstall the app or install any other version.

I use the ADT-1 mostly for Netflix, so unfortunately I had to reinstall the stock version :(

Keep up the good work!

**Comment by r3pwn** [comment]
@spipnl The first issue should be fixed soon. I haven't heard any reports of the second issue, but then again, I haven't tried it myself (I don't have a Netflix account). Thanks for the report. :)

**Comment by C457** [comment]
Don't forget to update your manifest 
https://github.com/adt1-dev/local_manifests/commit/f424b0ae6777d884db19fa5b3a281911518c3dbe

I've made changes to inherit the common nvidia sepolicy here https://github.com/Tegra4/android_device_nvidia_sepolicy

You now have a base to begin working on target specific denials. They should be added to the device and not the common repo.

**Comment by mknrls** [comment]
@C457 thanks man

**Comment by C457** [comment]
I also want to leave a note on android M. I have attempted to port it to the madcatz mojo and we also attempted with SHIELD portable. The GLESV2 driver crashes on boot for all Tegra 4 devices. So far we've been unable to track the issue down. Keep in mind I'm using adt-1 gpu blobs on my madcatz mojo for L compatibility due to my device shipping with 4.2.2.

Some stuff you may want to read http://dmitry.gr/index.php?r=06.%20Thoughts&proj=04.%20Android%20M%20on%20Grouper#cool_hacks

**Comment by mknrls** [comment]
@C457 out of curiosity did you get DRM stuff  (TV Build) working on the mojo?

**Comment by C457** [comment]
I'm using the adt-1 drm blobs so that's a no. Netflix does work on tablet builds though.

**Comment by r3pwn** [comment]
;)
